package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sun1tar/MIREA-TIP-Practice-27/tech-ip-sem2/graphql/internal/repository"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input CreateTaskInput) (*Task, error) {
	r.Resolver.Logger.WithField("title", input.Title).Info("creating task via GraphQL")

	now := time.Now()
	dbTask := &repository.Task{
		ID:          "t_" + uuid.New().String(),
		Title:       input.Title,
		Description: "",
		Done:        false,
		CreatedAt:   now,
		UpdatedAt:   now,
	}

	if input.Description != nil {
		dbTask.Description = *input.Description
	}

	if err := r.Resolver.Repo.Create(ctx, dbTask); err != nil {
		r.Resolver.Logger.WithError(err).Error("failed to create task")
		return nil, err
	}

	task := &Task{
		ID:          dbTask.ID,
		Title:       dbTask.Title,
		Description: &dbTask.Description,
		Done:        dbTask.Done,
	}

	r.Resolver.Logger.WithField("task_id", task.ID).Info("task created successfully via GraphQL")
	return task, nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input UpdateTaskInput) (*Task, error) {
	r.Resolver.Logger.WithField("task_id", id).Info("updating task via GraphQL")

	dbTask, err := r.Resolver.Repo.GetByID(ctx, id)
	if err != nil {
		if err == sql.ErrNoRows {
			r.Resolver.Logger.WithField("task_id", id).Warn("task not found for update")
			return nil, nil
		}
		r.Resolver.Logger.WithError(err).Error("failed to get task for update")
		return nil, err
	}
	if dbTask == nil {
		return nil, nil
	}

	if input.Title != nil {
		dbTask.Title = *input.Title
	}
	if input.Description != nil {
		dbTask.Description = *input.Description
	}
	if input.Done != nil {
		dbTask.Done = *input.Done
	}
	dbTask.UpdatedAt = time.Now()

	if err := r.Resolver.Repo.Update(ctx, dbTask); err != nil {
		r.Resolver.Logger.WithError(err).Error("failed to update task")
		return nil, err
	}

	task := &Task{
		ID:          dbTask.ID,
		Title:       dbTask.Title,
		Description: &dbTask.Description,
		Done:        dbTask.Done,
	}

	r.Resolver.Logger.WithField("task_id", id).Info("task updated successfully via GraphQL")
	return task, nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	r.Resolver.Logger.WithField("task_id", id).Info("deleting task via GraphQL")

	err := r.Resolver.Repo.Delete(ctx, id)
	if err == sql.ErrNoRows {
		r.Resolver.Logger.WithField("task_id", id).Warn("task not found for deletion")
		return false, nil
	}
	if err != nil {
		r.Resolver.Logger.WithError(err).Error("failed to delete task")
		return false, err
	}

	r.Resolver.Logger.WithField("task_id", id).Info("task deleted successfully via GraphQL")
	return true, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*Task, error) {
	r.Resolver.Logger.Info("listing tasks via GraphQL")

	dbTasks, err := r.Resolver.Repo.List(ctx)
	if err != nil {
		r.Resolver.Logger.WithError(err).Error("failed to list tasks")
		return nil, err
	}

	tasks := make([]*Task, len(dbTasks))
	for i, dbTask := range dbTasks {
		tasks[i] = &Task{
			ID:          dbTask.ID,
			Title:       dbTask.Title,
			Description: &dbTask.Description,
			Done:        dbTask.Done,
		}
	}

	r.Resolver.Logger.WithField("count", len(tasks)).Debug("tasks listed via GraphQL")
	return tasks, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*Task, error) {
	r.Resolver.Logger.WithField("task_id", id).Info("getting task via GraphQL")

	dbTask, err := r.Resolver.Repo.GetByID(ctx, id)
	if err != nil {
		if err == sql.ErrNoRows {
			r.Resolver.Logger.WithField("task_id", id).Warn("task not found")
			return nil, nil
		}
		r.Resolver.Logger.WithError(err).Error("failed to get task")
		return nil, err
	}

	if dbTask == nil {
		return nil, nil
	}

	task := &Task{
		ID:          dbTask.ID,
		Title:       dbTask.Title,
		Description: &dbTask.Description,
		Done:        dbTask.Done,
	}

	r.Resolver.Logger.WithField("task_id", id).Debug("task retrieved via GraphQL")
	return task, nil
}

// Description is the resolver for the description field.
func (r *taskResolver) Description(ctx context.Context, obj *Task) (*string, error) {
	return obj.Description, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Task returns TaskResolver implementation.
func (r *Resolver) Task() TaskResolver { return &taskResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type taskResolver struct{ *Resolver }
